# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

matrix:
  include:
  # linux builds
    # fedora builds
    #- os: linux
    #  compiler: clang
    #  r:
    #    - release
    #    - devel
    #  r_check_args: '--use-valgrind --as-cran'
    #  addons:
    #    apt:
    #      packages:
    #        - valgrind
    #  env: OS=fedora VALGRIND_OPTS='--leak-check=full --track-origins=yes'

    - os: linux
      compiler: gcc
      r:
        - release
        - devel
      r_check_args: '--use-valgrind --as-cran'
      addons:
        apt:
          packages:
            - valgrind
      env: OS=fedora VALGRIND_OPTS='--leak-check=full --track-origins=yes'

    # debian builds
    - os: linux
      compiler: gcc
      r:
        - release
        - devel
      r_check_args: '--use-valgrind --as-cran'
      addons:
        apt:
          packages:
            - valgrind
      env: OS=debian VALGRIND_OPTS='--leak-check=full --track-origins=yes'

    # solaris builds
    - os: linux
      compiler: gcc
      r:
        - release
        - devel
      r_check_args: '--use-valgrind --as-cran'
      addons:
        apt:
          packages:
            - valgrind
      env: OS=solaris VALGRIND_OPTS='--leak-check=full --track-origins=yes'

  # macOS builds
    - os: osx
      r:
        - release
        - devel
      r_check_args: '--use-valgrind --as-cran'
      addons:
        apt:
          packages:
            - valgrind
      env: OS=fedora VALGRIND_OPTS='--leak-check=full --track-origins=yes'

r_packages:
  - covr

# Report coverage for the release version.
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
