# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  # linux builds
     fedora builds
    - os: linux
      compiler: clang
      r: release
      r_check_args: '--as-cran'
      env: OS=fedora

    - os: linux
      compiler: gcc
      r: release
      r_check_args: '--as-cran'
      env: OS=fedora

    - os: linux
      compiler: clang
      r: devel
      r_check_args: '--as-cran'
      env: OS=fedora

    - os: linux
      compiler: gcc
      r: devel
      r_check_args: '--as-cran'
      env: OS=fedora

    - os: linux
      compiler: gcc
      r: release
      r_check_args: '--as-cran'
      env: OS=debian'
      # Report coverage for this build (release on debian).
      r_packages:
        - covr
      after_success:
        - Rscript -e 'covr::codecov()'

    - os: linux
      compiler: gcc
      r: devel
      r_check_args: '--as-cran'
      env: OS=debian'

    - os: osx
      r: release
      r_check_args: '--as-cran'

    - os: osx
      r: devel
      r_check_args: '--as-cran'


notifications:
  email: false