# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

# covr does not work on the combination of osx devel on travis-ci.
matrix:
  exclude:
  - os: osx
    r: devel

# Report coverage for the release version.
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'