# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  matrix:
    - OS=fedora
    - OS=ubuntu
    - OS=debian

r_packages:
  - covr

# Report coverage for the release version.
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
