# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      r: release
      r_check_args: '--as-cran'
      env: OS=ubuntu

    - os: linux
      r: devel
      r_check_args: '--as-cran'
      env: OS=ubuntu

    - os: linux
      compiler: clang
      r: release
      r_check_args: '--as-cran'
      env: OS=fedora

    - os: linux
      compiler: gcc
      r: release
      r_check_args: '--as-cran'
      env: OS=fedora

    - os: linux
      compiler: clang
      r: devel
      r_check_args: '--as-cran'
      env: OS=fedora

    - os: linux
      compiler: gcc
      r: devel
      r_check_args: '--as-cran'
      env: OS=fedora

    - os: linux
      compiler: gcc
      r: release
      r_check_args: '--as-cran'
      env: OS=debian'

    - os: linux
      compiler: gcc
      r: devel
      r_check_args: '--as-cran'
      env: OS=debian'

    - os: osx
      r: release
      r_check_args: '--as-cran'


# Report coverage.
r_packages:
  - covr
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'


notifications:
  email: true
