# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

r:
  - oldrel
  - release
  - devel

r_check_args: '--use-valgrind --as-cran'

addons:
  apt:
    packages:
      - valgrind

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'

matrix:
  include:
  # linux builds
    # fedora builds
    - os: linux
      compiler: clang
      env: OS=fedora

    - os: linux
      compiler: gcc
      env: OS=fedora

    # debian builds
    - os: linux
      compiler: gcc
      env: OS=debian

    # solaris builds
    - os: linux
      compiler: gcc
      env: OS=solaris
  # macOS builds
    # solaris builds
    - os: osx

r_packages:
  - covr

# Report coverage for the release version.
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
