# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

matrix:
  include:
  # linux builds
    # fedora builds
    #- os: linux
    #  compiler: clang
    #  r:
    #    - release
    #    - devel
    #  r_check_args: '--use-valgrind --as-cran'
    #  addons:
    #    apt:
    #      packages:
    #        - valgrind
    #  env: OS=fedora VALGRIND_OPTS='--leak-check=full --track-origins=yes'

    - os: linux
      compiler: gcc
      r:
        - release
      r_check_args: '--use-valgrind --as-cran'
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq valgrind
      env: OS=fedora VALGRIND_OPTS='--leak-check=full --track-origins=yes'



r_packages:
  - covr

# Report coverage for the release version.
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
