# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Group PALM/iPALM localizations based on their physical separation distance
#'
#' PALM/iPALM data results in a list of spatial coordinates for fluorophore
#' localizations. This function groups nearby localizations if they are within
#' the provided critical distance from each other.
#'
#' @title Return the group number for each localization.
#'
#' @param input A numeric matrix where each row is a localization and each
#' column is a spatial axis.
#' @param critDist The critical distance for which localizations nearer than
#' this distance are deemed part of the same group.
#' @author Zach Colburn
#' @examples
#' # Function call
#' euclidean_linker(inputMatrix,critDist)
#'
euclidean_linker <- function(input, critDist) {
    .Call(`_Bioi_euclidean_linker`, input, critDist)
}

#' Find the shortest distance between each point in one data set and the points
#' in a second set.
#'
#' This function determines the distance between every point in data set 1 and
#' the points in data set 2. Unlike this function's naive counterpart,
#' find_min_dists, this function divides the PALM/iPALM localization data
#' into blocks, opeartes on the data in each block, and then performs linking
#' operations on neighboring blocks.
#'
#' @title For all points in matrix 1, return the distance and index of the
#' nearest point in matrix 2.
#'
#' @param mOne A numeric matrix where each row is a localization and each
#' column is a spatial axis.
#' @param mTwo A matrix with the same number of columns as mOne.
#' @author Zach Colburn
#' @examples
#' # Function call
#' find_min_dists(mOne, mTwo)
#'
find_min_dists <- function(mOne, mTwo) {
    .Call(`_Bioi_find_min_dists`, mOne, mTwo)
}

#' Group continuous, thresholded objects in rasterized objects.
#'
#' This function takes a matrix corresponding to a thresholded image and
#' returns a matrix of the same size, where all adjacent, thesholded pixels
#' are the same integer corresponding to that object's cluster number.
#'
#' @title Assign all neighboring pixels the same group number.
#'
#' @param img A thresholded matrix (where non-object pixels are assigned a
#' value of 0).
#' @param pixRange An integer number of pixels. Execution is faster when this
#' value is small. However, the value must be larger than the diameter of the
#' largest continuous object in the image.
#' @author Zach Colburn
#' @examples
#' # Function call
#' identify_thresholded_objects(img, pixRange)
#'
identify_thresholded_objects <- function(img, pixRange) {
    .Call(`_Bioi_identify_thresholded_objects`, img, pixRange)
}

#' Identify the local shift between two temporally separated images.
#'
#' This function determines the local shift between two temporally separated
#' images. It does so by minimizing the squared difference between a local
#' template centered on the supplied peg coordinates and adjacent matrices of
#' the same dimension.
#'
#' @title Identify the local shift between two temporally separated images.
#'
#' @param t0 A numeric matrix of intensity values for the first image.
#' @param t1 A numeric matrix of intensity values for the second image.
#' @param xSeq A numeric vector of the x coordinates defining template centers.
#' @param ySeq A numeric vector of the y coordinates defining template centers.
#' @param searchBoxRadius An integer defining the search box radius.
#' @param matchBoxRadius An integer defining the radius of templates.
#' @param shiftSkipper An integer defining the number of pixels away the next
#' template to image comparison will be. This value must be 1 or greater.
#' Larger values will dramatically reduce execution time, but can reduce data
#' quality.
#' @author Zach Colburn
#' @examples
#' # Function call
#' shifter(t0, t1, xSeq, ySeq, searchBoxRadius, matchBoxRadius, shiftSkipper)
#'
shifter <- function(t0, t1, xSeq, ySeq, searchBoxRadius, matchBoxRadius, shiftSkipper) {
    .Call(`_Bioi_shifter`, t0, t1, xSeq, ySeq, searchBoxRadius, matchBoxRadius, shiftSkipper)
}

